version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bankchu-core-banking-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      # SQL Server
      ConnectionStrings__DefaultConnection: >
        Server=db;
        Database=BankChuCoreBanking;
        User Id=sa;
        Password=BancoChu@1;
        TrustServerCertificate=True;

      # Redis
      ConnectionStrings__Redis: redis:6379
      
      # BrasilAPI
      ExternalApis__BrasilApi__BaseUrl: https://brasilapi.com.br
      ExternalApis__BrasilApi__TimeoutSeconds: 60
    depends_on:
      - db
      - redis

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bankchu-sqlserver
    environment:
      SA_PASSWORD: "BancoChu@1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
    - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P BancoChu@1 -Q \"SELECT 1\""]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: bankchu-redis
    ports:
      - "6379:6379"

volumes:
  sqlserver_data: