<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BankChu.CoreBanking.Application\BankChu.CoreBanking.Application.csproj" />
    <ProjectReference Include="..\BankChu.CoreBanking.Infrastructure\BankChu.CoreBanking.Infrastructure.csproj" />
  </ItemGroup>

</Project>
